### ISSUE TITLE
Unraid develop update issue

### ISSUE THREAD

**Issue by cwills75** [a1ex4/ownfoil#142] opened 2024-11-05 15:28 UTC
Running this on an Unraid server in docker, using the develop branch.  Saw there was an update so I ran it.  The Library page works, but the Settings page gives me this error in the browser:

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I removed the docker and re-added it with the non-develop branch and it's working again.

**Comment by loadedlouie** [comment] 2024-11-06 11:23
i think titledb.zip is missing and breaking the start of the app

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nightly.link', port=443): Max retries exceeded with url: /a1ex4/ownfoil/workflows/region_titles/master/titledb.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1509abee6250>: Failed to resolve 'nightly.link' ([Errno -3] Try again)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 387, in <module>
    init()
  File "/app/app.py", line 36, in init
    titledb.update_titledb(app_settings)
  File "/app/titledb.py", line 87, in update_titledb
    update_titledb_files(app_settings)
  File "/app/titledb.py", line 66, in update_titledb_files
    r = requests.get(TITLEDB_ARTEFACTS_URL, allow_redirects = False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nightly.link', port=443): Max retries exceeded with url: /a1ex4/ownfoil/workflows/region_titles/master/titledb.zip (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x1509abee6250>: Failed to resolve 'nightly.link' ([Errno -3] Try again)"))
users:x:100:games,ownfoil
ownfoil:x:99:100:Linux User,,,:/home/ownfoil:/sbin/nologin
Starting ownfoil
[2024-11-06 11:18:13.687] INFO (app) Starting initialization of Ownfoil...
[2024-11-06 11:18:13.687] INFO (app) Initializing File Watcher...
[2024-11-06 11:18:13.688] INFO (app) Loading initial configuration...
[2024-11-06 11:18:13.689] DEBUG (settings) Reading configuration file.
[2024-11-06 11:18:13.692] DEBUG (settings) Keys file /app/config/keys.txt does not exist.
[2024-11-06 11:18:13.692] INFO (file_watcher) Adding directory /games to watchdog.
[2024-11-06 11:18:13.731] INFO (titledb) Updating titledb...

** Press ANY KEY to close this window **

**Comment by a1ex4** [comment] 2024-12-09 22:36
Thanks for the report, it was an issue with the service used to redirect to the latest titledb build that was down, see #148.

**Closed by a1ex4** 2024-12-09 22:36 UTC
