### ISSUE TITLE
Unraid image memory leaks when scanning library

### ISSUE THREAD

**Issue by maxistviews** [a1ex4/ownfoil#113] opened 2024-09-01 17:32 UTC
![image](https://github.com/user-attachments/assets/0403f8d7-e44b-4836-85df-c758d01133c1)

My title keys are not accepted until eventually they are, so maybe that has something to do with it. I click Scan Library and eventually, my entire server stops responding and needs to be restarted.

Unraid 6.12.11

**Comment by mzaki83** [comment] 2024-09-01 22:58
Docker memory leak here as well. Running develop branch using docker compose in debian.

**Comment by a1ex4** [comment] 2024-09-04 21:35
Seems like a duplicate of #111, let's continue there.

**Closed by a1ex4** 2024-09-04 21:35 UTC
